mstcn_epoch: 1000
batch_size: 16
processed_clip_dir: /videoclips
videomae_model_path: ./checkpoints/vmae/vmae_checkpoint.pth
feature_save_dir: /features
mstcn_checkpoint: ./checkpoints/mstcn/mstcn_checkpoint.pth