train_dir: /mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/mstcn-features/train
val_dir: /mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/mstcn-features/val
test_dir: /mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/mstcn-features/test
wandb_api_key: "3cd0fd46806f5dbb7e666990676fb3d1c75e0447"
log_dir: logs
checkpoint_dir: checkpoints/mstcn/grad-clipped
max_epochs: 300
mstcn_stages: 2
mstcn_layers: 10
mstcn_f_maps: 64
mstcn_f_dim: 768
out_features: 7
mstcn_causal_conv: True
devices: 1
batch_size: 4
num_workers: 8
learning_rate: 0.001
optimizer_name: adam