mstcn_epoch: 1000
batch_size: 16
#processed_clip_dir: "/mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/final-data/"
processed_clip_dir: "/mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/test_spilit"
videomae_model_path: "./checkpoints/vmae/videomae_pretraining_epoch_319.pth"
#feature_save_dir: "/mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/mstcn-features/"
feature_save_dir: "/mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/test_spilit/test-features" # Change it "./features"
mstcn_checkpoint: "./checkpoints/mstcn/mstcn_checkpoint.pth"
main_data_source_folder: "/mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/test_spilit/"