# === Paths ===
train_dir: /mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/test_spilit/test-features/train
val_dir: /mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/test_spilit/test-features/val
test_dir: /mnt/ceph/tco/TCO-Students/Homes/debashis/data/processed/test_spilit/test-features/test

log_dir: logs
checkpoint_dir: /mnt/ceph/tco/TCO-Students/Homes/debashis/vmae-mstcn/checkpoints/mstcn/
checkpoint_file: epoch=8-step=279.ckpt  # Name of the checkpoint file to load for visualization

# Model-specific parameters
mstcn_stages: 2
mstcn_layers: 10
mstcn_f_maps: 64
mstcn_f_dim: 768
out_features: 7
mstcn_causal_conv: True
devices: 1
batch_size: 4
num_workers: 8
learning_rate: 0.001
optimizer_name: adam
accelerator: gpu